import type { ErrorCodeDefinition } from '../types';

// Keep in sync with CURRENT_VERSION in ../codes.ts (local copy avoids a
// circular import).
const V = '3.2.29';

export const WEBSOCKET_CODES: readonly ErrorCodeDefinition[] = [
  {
    code: 'QPM-WS-001',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'No active connection',
    description: 'sendRoomAction() called before a room connection was established.',
    userAction: 'Reconnect to the game (refresh the tab if it persists).',
    devNotes: 'src/websocket/api.ts — guards against missing MagicCircle_RoomConnection.',
    sinceVersion: V,
    // §9 — fires only during user-driven sends; user can act (reconnect/refresh); not transient
    // (each fire is a real failed action). Default warn throttle (30s) suppresses send-spam.
    notifyUser: true,
  },
  {
    code: 'QPM-WS-002',
    subsystem: 'websocket',
    category: 'core',
    severity: 'info',
    title: 'Throttled',
    description: 'sendRoomAction() was throttled by the per-key rate limit.',
    devNotes: 'src/websocket/api.ts — throttle bucket per (type, key).',
    sinceVersion: V,
  },
  {
    code: 'QPM-WS-003',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'WebSocket send failed',
    description: 'sendRoomAction() returned ok:false from the underlying connection.',
    devNotes: 'src/websocket/api.ts — non-ok return path.',
    sinceVersion: V,
  },
  {
    code: 'QPM-WS-004',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Invalid payload',
    description: 'sendRoomAction() rejected a payload that failed validation.',
    devNotes: 'src/websocket/api.ts — validatePayload(); likely a caller bug.',
    sinceVersion: V,
  },
  {
    code: 'QPM-WS-005',
    subsystem: 'websocket',
    category: 'core',
    severity: 'info',
    title: 'Locker blocked send',
    description: 'A registered preflight (locker guard) blocked the send.',
    devNotes: 'src/websocket/api.ts — registerSendPreflight() returned ok:false.',
    sinceVersion: V,
  },
  {
    code: 'QPM-WS-006',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'QuinoaCommand rejected',
    description: 'The server returned ok:false for a QPM-originated QuinoaCommand envelope.',
    devNotes: 'src/websocket/commandSequencer.ts — context.code is the server code (invalid_sequence retries once).',
    sinceVersion: '3.3.31',
  },
  {
    code: 'QPM-WS-007',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'QuinoaCommand result timeout',
    description: 'No QuinoaCommandResult arrived within 5 s — outcome unknown (stale/duplicate sequences are dropped silently).',
    devNotes: 'src/websocket/commandSequencer.ts — usually a sequence desync; check getCommandSequencerStats().',
    sinceVersion: '3.3.31',
  },
  {
    code: 'QPM-WS-008',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Command sequencer attach failed',
    description: 'The command sequencer could not (re)wrap the room connection send functions; QPM falls back to legacy flat sends. phase:attach/rearm = the install threw; phase:layering with qpmBranded = QPM outer wrappers sit directly over the prototype with no re-armable sequencer wrapper below (refresh resolves). Third-party layering refusals are QPM-WS-013.',
    devNotes: 'src/websocket/commandSequencer.ts ensureAttached()/rearm().',
    sinceVersion: '3.3.31',
  },
  {
    code: 'QPM-WS-009',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Transport allowlist out of date',
    description: 'The game (or a not_ackable verdict) showed a type uses a different transport than LEGACY_ROOM_ACTION_TYPES predicts. QPM mirrors the observed transport automatically.',
    devNotes: 'src/websocket/transport.ts — update LEGACY_ROOM_ACTION_TYPES in envelope.ts; run __QPM_INTERNAL__.commandSequencer.transportAudit().',
    sinceVersion: '3.3.31',
  },
  {
    code: 'QPM-WS-010',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Send budget exhausted',
    description: 'A QPM action was refused locally (reason: throttled) because QPM\'s share of the socket-wide command budget (server: ~300 per ~10 s) was used up. A feature is sending in a tight loop.',
    devNotes: 'src/websocket/transport.ts takeSendToken() — 30 burst, 10/s sustained. Check __QPM_INTERNAL__.commandSequencer.sendBudget().',
    sinceVersion: '3.3.31',
  },
  {
    code: 'QPM-WS-011',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Envelope skipped pre-session',
    description: 'A QuinoaCommand envelope reached sendMessage before Welcome; the sequencer skipped rewrite (fires once per session) so a burned commandSequence would not desync subsequent envelopes.',
    devNotes: 'src/websocket/commandSequencer.ts — check stats().skippedPreSession. A non-zero count means QPM built an envelope before isCommandSessionReady turned true.',
    sinceVersion: V,
  },
  {
    code: 'QPM-WS-012',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'QuinoaCommand dropped (stale)',
    description: 'A room frame advanced past this envelope\'s commandSequence without a matching QuinoaCommandResult. The server dropped the send silently (rule: stale/duplicate numbers → no result). Definite rejection; the caller may choose to resend.',
    devNotes: 'src/websocket/commandSequencer.ts — grace: qpm.ws.sequencer.staleGraceMs (default 750 ms). Toggle: qpm.ws.sequencer.staleDetect.enabled. Check stats().dropped and stats().idleResyncs (a drop triggers CS-1 heal when nothing else is outstanding).',
    sinceVersion: V,
  },
  {
    code: 'QPM-WS-013',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Unexpected wrapper on the game connection',
    description: 'An own-property wrapper sits on the room connection send functions, so the command sequencer cannot layer innermost (CS-5). Either a third-party script wrapped the connection, or QPM\'s own outer wrappers / bound-copy restores were left behind by a mid-session detach (CS-5 cannot yet tell these apart). QPM falls back to legacy flat sends until it clears. Fires once per episode, not per check.',
    userAction: 'If other Magic Garden mods are running, disable them and refresh. If this appears with no other mods, refresh the tab — actions may silently stop registering until you do — and please report it.',
    devNotes: 'src/websocket/commandSequencer.ts ensureAttached() — warns after 3 consecutive refused checks; clear logged at info with episode duration. stats().layeringRefusals counts every refused check. Self-inflicted case: detach() cannot restore under outer wrappers and may leave a rewriting wrappedSend in the chain with frozen counters — see the wrapper-lifecycle fix plan.',
    sinceVersion: '3.3.42',
    // §9 — degraded sequencing affects the user's actions; userAction is real
    // (disable the other mod); the 3-check episode gate proves non-transience.
    notifyUser: true,
  },
];
