import type { ErrorCodeDefinition } from '../types';

// Keep in sync with CURRENT_VERSION in ../codes.ts (local copy avoids a
// circular import).
const V = '3.2.29';

export const WEBSOCKET_CODES: readonly ErrorCodeDefinition[] = [
  {
    code: 'QPM-WS-001',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'No active connection',
    description: 'sendRoomAction() called before a room connection was established.',
    userAction: 'Reconnect to the game (refresh the tab if it persists).',
    devNotes: 'src/websocket/api.ts — guards against missing MagicCircle_RoomConnection.',
    sinceVersion: V,
    // §9 — fires only during user-driven sends; user can act (reconnect/refresh); not transient
    // (each fire is a real failed action). Default warn throttle (30s) suppresses send-spam.
    notifyUser: true,
  },
  {
    code: 'QPM-WS-002',
    subsystem: 'websocket',
    category: 'core',
    severity: 'info',
    title: 'Throttled',
    description: 'sendRoomAction() was throttled by the per-key rate limit.',
    devNotes: 'src/websocket/api.ts — throttle bucket per (type, key).',
    sinceVersion: V,
  },
  {
    code: 'QPM-WS-003',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'WebSocket send failed',
    description: 'sendRoomAction() returned ok:false from the underlying connection.',
    devNotes: 'src/websocket/api.ts — non-ok return path.',
    sinceVersion: V,
  },
  {
    code: 'QPM-WS-004',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Invalid payload',
    description: 'sendRoomAction() rejected a payload that failed validation.',
    devNotes: 'src/websocket/api.ts — validatePayload(); likely a caller bug.',
    sinceVersion: V,
  },
  {
    code: 'QPM-WS-005',
    subsystem: 'websocket',
    category: 'core',
    severity: 'info',
    title: 'Locker blocked send',
    description: 'A registered preflight (locker guard) blocked the send.',
    devNotes: 'src/websocket/api.ts — registerSendPreflight() returned ok:false.',
    sinceVersion: V,
  },
  {
    code: 'QPM-WS-006',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'QuinoaCommand rejected',
    description: 'The server returned ok:false for a QPM-originated QuinoaCommand envelope.',
    devNotes: 'src/websocket/commandSequencer.ts — context.code is the server code (invalid_sequence retries once).',
    sinceVersion: '3.3.31',
  },
  {
    code: 'QPM-WS-007',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'QuinoaCommand result timeout',
    description: 'No QuinoaCommandResult arrived within 5 s — outcome unknown (stale/duplicate sequences are dropped silently).',
    devNotes: 'src/websocket/commandSequencer.ts — usually a sequence desync; check getCommandSequencerStats().',
    sinceVersion: '3.3.31',
  },
  {
    code: 'QPM-WS-008',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Command sequencer attach failed',
    description: 'The command sequencer could not install or re-arm; QPM falls back to legacy flat sends. phase:attach/rearm = the install threw (mode says which). phase:layering with qpmBranded = QPM outer wrappers sit on sendMessage/trySendMessageNow with no sequencer slot wrapper below: the sequencer kill switch was off when they installed, or the chokepoint was bypassed mid-session (QPM-WS-015 precedes it). A reload with the switch on re-orders the chain. Third-party wrappers are QPM-WS-013.',
    devNotes: 'src/websocket/sequencerAttach.ts attachSlots()/rearm()/attachChokepoint()/rearmChokepoint().',
    sinceVersion: '3.3.31',
  },
  {
    code: 'QPM-WS-009',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Transport allowlist out of date',
    description: 'The game (or a not_ackable verdict) showed a type uses a different transport than LEGACY_ROOM_ACTION_TYPES predicts. QPM mirrors the observed transport automatically.',
    devNotes: 'src/websocket/transport.ts — update LEGACY_ROOM_ACTION_TYPES in envelope.ts; run __QPM_INTERNAL__.commandSequencer.transportAudit().',
    sinceVersion: '3.3.31',
  },
  {
    code: 'QPM-WS-010',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Send budget exhausted',
    description: 'A QPM action was refused locally (reason: throttled) because QPM\'s share of the socket-wide command budget (server: ~300 per ~10 s) was used up. A feature is sending in a tight loop.',
    devNotes: 'src/websocket/transport.ts takeSendToken() — 30 burst, 10/s sustained. Check __QPM_INTERNAL__.commandSequencer.sendBudget().',
    sinceVersion: '3.3.31',
  },
  {
    code: 'QPM-WS-011',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Envelope skipped pre-session',
    description: 'A QuinoaCommand envelope reached a send wrapper before Welcome; the sequencer skipped rewrite (fires once per session) so a burned commandSequence would not desync subsequent envelopes.',
    devNotes: 'src/websocket/commandSequencer.ts — check stats().skippedPreSession. Since game 1195 both send slots refuse/queue until Welcome, so a non-zero count means an older bundle, a foreign wrapper calling the chokepoint directly, or the game flushing its pre-Welcome queue through the wrappers.',
    sinceVersion: V,
  },
  {
    code: 'QPM-WS-016',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Send refused: command session not ready',
    description: 'A QPM action was refused locally (reason: session_not_ready) because the socket is open but the server has not sent Welcome yet. Since game 1195 the client sends SocketOpened on open and the server admits the socket with Welcome (10 s server timeout, 15 s client watchdog); nothing may be sent in between. Fires once per admission window; a successful send re-arms it.',
    devNotes: 'src/websocket/api.ts transmitRoomAction() — wsCounters.sessionNotReady. Feature gates use isRoomSessionReady(), not isRoomSocketOpen(). A rising count with a stuck "waiting for Welcome" bus row means the server never admitted the socket (auth/room transition); the game reconnects on its own.',
    sinceVersion: '3.3.49',
  },
  {
    code: 'QPM-WS-012',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'QuinoaCommand dropped (stale)',
    description: 'A room frame advanced past this envelope\'s commandSequence without a matching QuinoaCommandResult. The server dropped the send silently (rule: stale/duplicate numbers → no result). Definite rejection; the caller may choose to resend.',
    devNotes: 'src/websocket/commandSequencer.ts — grace: qpm.ws.sequencer.staleGraceMs (default 750 ms). Toggle: qpm.ws.sequencer.staleDetect.enabled. Check stats().dropped and stats().idleResyncs (a drop triggers CS-1 heal when nothing else is outstanding).',
    sinceVersion: V,
  },
  {
    code: 'QPM-WS-013',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Unexpected wrapper on the game connection',
    description: 'An own-property wrapper sits where the command sequencer must install, so it cannot layer innermost. phase:layering = a third-party wrapper on sendMessage/trySendMessageNow (slot mode; warns after 3 checks over 3 s). phase:buried = QPM\'s own outer wrappers were installed over such a wrapper (slot mode; warns at once). phase:chokepoint = a wrapper already sits on the game\'s internal send method (chokepoint mode; warns at once). QPM falls back to legacy flat sends until it clears. Fires once per episode, not per check.',
    userAction: 'If other Magic Garden mods are running, disable them and refresh. If this appears with no other mods, refresh the tab — actions may silently stop registering until you do — and please report it.',
    devNotes: 'src/websocket/sequencerAttach.ts attachSlots()/attachChokepoint() — stats().layeringRefusals counts every refused check; __QPM_INTERNAL__.commandSequencer.chain() lists every layer top→bottom.',
    sinceVersion: '3.3.42',
    // §9 — degraded sequencing affects the user's actions; userAction is real
    // (disable the other mod); the 3-check episode gate proves non-transience.
    notifyUser: true,
  },
  {
    code: 'QPM-WS-014',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'QuinoaCommand sequence number went unanswered',
    description: 'A commandSequence was put on the wire, the room never executed it, and the server never replied — the signature of a stale/duplicate number, which the server answers with silence. QPM marks the number spent and biases the next allocation past it so the counter cannot re-emit a dead number forever. Self-healing; no user action.',
    devNotes: 'src/websocket/commandSequencer.ts onTimeout() — sets `unansweredFloor`; see stats().unansweredProbes, stats().frontierCatchUps, and compare stats().frontier with stats().roomExecuted. Fires at most once per spent number. A rising count with a flat `frames` means the room-frame subscription stopped delivering executedCommandSequence.',
    sinceVersion: '3.3.46',
  },
  {
    code: 'QPM-WS-015',
    subsystem: 'websocket',
    category: 'core',
    severity: 'warn',
    title: 'Command sequencer chokepoint bypassed',
    description: 'A QPM QuinoaCommand reached the server without a sequence number (invalid_message) while the command sequencer was installed on the game\'s internal send method — another script replaced that method without calling through, or the game changed its send path. QPM moved this connection to slot mode for the session; if QPM\'s own outer wrappers already sit on the send functions, QPM-WS-008 follows and QPM uses legacy flat sends until the page is reloaded.',
    devNotes: 'src/websocket/sequencerAttach.ts reportBypass() — stats().chokepointBypassed; inspect __QPM_INTERNAL__.commandSequencer.chain() (T5). Discovery rule: src/websocket/sendChokepoint.ts.',
    sinceVersion: '3.3.47',
  },
];
